const genreData = [
  {id:'animals', name:'どうぶつ', emoji:'🐾', unlocked:true, words:[['ねこ','cat','assets/cat.png'],['いぬ','dog','assets/dog.png'],['とり','bird','assets/bird.png']]},
  {id:'food', name:'たべもの', emoji:'🍎', unlocked:true, words:[['りんご','apple','assets/apple.png'],['パン','bread','assets/bread.png'],['ケーキ','cake','assets/cake.png']]},
  {id:'school', name:'がっこう', emoji:'🎒', unlocked:false, words:[['かばん','backpack','assets/backpack.png'],['ほん','book','assets/book.png'],['えんぴつ','pencil','assets/pencil.png']]},
  {id:'colors', name:'いろ', emoji:'🎨', unlocked:false, words:[['あか','red','assets/red.png'],['あお','blue','assets/blue.png'],['きいろ','yellow','assets/yellow.png']]},
  {id:'weather', name:'てんき', emoji:'☀️', unlocked:false, words:[['たいよう','sun','assets/sun.png'],['あめ','rain','assets/rain.png'],['ゆき','snow','assets/snow.png']]}
];
let activeGenreId = 'animals';
let cards = buildCards(genreData[0]);
let pendingMode = 'cards';
const progress = JSON.parse(localStorage.getItem('eigo-progress') || '{}');
const unlockedIds = new Set(progress.__unlocked || genreData.filter(g=>g.unlocked).map(g=>g.id));
genreData.forEach(g=>{g.unlocked=unlockedIds.has(g.id)});
function genreProgress(id){return progress[id] ||= {treasure:false, quiz:false, speak:false, pair:false, master:false};}
function buildCards(genre){return genre.words.map(([jp,en,img])=>({jp,en,img,hint:`${genre.name}の ことばだよ。`,example:`I like ${en}.`,translation:`${jp}が すきです。`}));}
let cardIndex = 0, quizIndex = 0, speakIndex = 0, pairIndex = 0, quizCorrect = new Set(), speakCorrect = new Set(), pairCorrect = new Set();
const $ = s => document.querySelector(s);
function renderGenres(){
  const row=$('.genre-row'); row.innerHTML=genreData.map(g=>{const p=genreProgress(g.id); return `<button class="genre ${g.id===activeGenreId?'selected':''} ${g.unlocked?'':'locked'}" data-genre="${g.id}" ${g.unlocked?'':'disabled'}>${g.emoji}<span>${g.name}</span><em>${g.unlocked?(p.treasure?'✅':'3こ'):'🔒'}</em></button>`}).join('');
  row.querySelectorAll('.genre:not(:disabled)').forEach(b=>b.addEventListener('click',()=>{const g=genreData.find(x=>x.id===b.dataset.genre); activeGenreId=g.id; cards=buildCards(g); cardIndex=quizIndex=speakIndex=pairIndex=0; $('#cards h2').textContent=`${g.name}の ことば`; renderGenres(); renderCard();}));
}
function showView(id) { document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === id)); window.scrollTo({top:0, behavior:'smooth'}); if (id === 'cards') renderCard(); if (id === 'quiz') renderQuiz(); if (id === 'speak') renderSpeak(); if (id === 'pair') renderPair(); if (id === 'today') renderToday(); if (id === 'categorySelect') renderCategorySelect(); }
function showCategorySelect(mode){pendingMode=mode; showView('categorySelect');}
document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => {const id=b.dataset.view; if(['cards','quiz','speak','pair'].includes(id)) showCategorySelect(id); else showView(id);}));
function renderCategorySelect(){const list=$('#categoryList'); list.innerHTML=genreData.map(g=>{const p=genreProgress(g.id); const allowed=g.unlocked && (pendingMode==='cards' || p.treasure); const badge=p.master?'🏆':p.treasure?'✅':''; return `<button class="category-choice ${allowed?'':'locked'}" data-genre="${g.id}" ${allowed?'':'disabled'}><span class="category-emoji">${g.emoji}</span><span><b>${g.name}</b><small>${allowed?(pendingMode==='cards'?'ことばを おぼえる':'れんしゅうに ちょうせん'):'🔒 たからばこクリアで開放'}</small></span><strong>${badge}</strong></button>`}).join(''); list.querySelectorAll('.category-choice:not(:disabled)').forEach(b=>b.addEventListener('click',()=>startCategory(b.dataset.genre)))}
function startCategory(id){const g=genreData.find(x=>x.id===id); activeGenreId=id; cards=buildCards(g); cardIndex=quizIndex=speakIndex=pairIndex=0; quizCorrect.clear(); speakCorrect.clear(); pairCorrect.clear(); $('#cards h2').textContent=`${g.name}の ことば`; showView(pendingMode);}
function showClear(message, nextMode){$('#clearTitle').textContent=`${genreData.find(g=>g.id===activeGenreId)?.name||''}カテゴリ クリア！`; $('#clearMessage').textContent=message; $('#clearContinue').textContent=nextMode==='quiz'?'問題に ちょうせん　›':'ホームへ　›'; $('#clearContinue').dataset.nextMode=nextMode||'home'; showView('clear');}
$('#clearContinue').addEventListener('click',()=>{const mode=$('#clearContinue').dataset.nextMode; if(mode==='home')showView('home'); else showCategorySelect(mode);});
function renderCard() {
  const c = cards[cardIndex]; $('#wordImage').src = c.img; $('#wordImage').alt = c.en+'のイラスト'; $('#wordJp').textContent = c.jp; $('#wordEn').textContent = c.en; $('#wordHint').textContent = c.hint; $('#wordExample').textContent = c.example; $('#wordExample').nextElementSibling.textContent = c.translation; $('#cardCount').textContent = `${cardIndex+1} / ${cards.length}`; $('#cardDots').innerHTML = cards.map((_,i) => `<i class="${i===cardIndex?'active':''}"></i>`).join('');
}
function completeMode(mode){const p=genreProgress(activeGenreId); p[mode]=true; if(p.treasure&&p.quiz&&p.speak&&p.pair){p.master=true; const next=genreData.find(g=>!g.unlocked); if(next){next.unlocked=true; unlockedIds.add(next.id); p.unlockMessage=`${next.name}がアンロックされたよ！`;}} progress.__unlocked=[...unlockedIds]; localStorage.setItem('eigo-progress',JSON.stringify(progress));}
$('#nextCard').addEventListener('click', () => { if(cardIndex===cards.length-1){completeMode('treasure'); showClear('たからばこクリア！ れんしゅうがアンロックされたよ。','quiz'); return;} cardIndex++; renderCard(); });
function renderQuiz() {
  const c = cards[quizIndex]; $('#quizImage').src = c.img; $('#quizImage').alt = c.jp+'のイラスト'; $('#quizCount').textContent = `${quizIndex+1} / ${cards.length}`; $('#result').textContent = ''; $('#result').className = 'result'; $('#nextQuiz').disabled = true;
  const options = [c.en, ...cards.filter((_,i)=>i!==quizIndex).map(x=>x.en)].sort(() => Math.random()-.5); $('#choices').innerHTML = options.map(x => `<button class="choice" data-answer="${x}">${x}</button>`).join(''); document.querySelectorAll('.choice').forEach(b => b.addEventListener('click', () => answer(b, c.en)));
}
function answer(btn, correct) { document.querySelectorAll('.choice').forEach(b => b.disabled = true); if (btn.dataset.answer === correct) { quizCorrect.add(quizIndex); btn.classList.add('correct'); $('#result').textContent = 'せいかい！ すごいね 🎉'; $('#result').classList.add('ok'); } else { btn.classList.add('wrong'); $('#result').textContent = `おしい！ せいかいは「${correct}」だよ。`; $('#result').classList.add('ng'); document.querySelector(`[data-answer="${correct}"]`).classList.add('correct'); } $('#nextQuiz').disabled = false; }
$('#nextQuiz').addEventListener('click', () => { if(quizIndex===cards.length-1){if(quizCorrect.size===cards.length){completeMode('quiz'); showClear('このジャンルの問題を ぜんぶ正解したよ！','home'); return;} quizCorrect.clear(); quizIndex=0; renderQuiz(); return;} quizIndex++; renderQuiz(); });
function renderSpeak(){const c=cards[speakIndex]; $('#speakImage').src=c.img; $('#speakImage').alt=c.en+'のイラスト'; $('#speakEn').textContent=c.en; $('#speakCount').textContent=`${speakIndex+1} / ${cards.length}`; $('#speakResult').textContent='まずは おてほんを きいてみよう。'; $('#speakResult').className='result'; $('#nextSpeak').disabled=!speakCorrect.has(speakIndex);}
$('#speakSample').addEventListener('click',async()=>{const c=cards[speakIndex]; try{const r=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:c.en,target:c.en})}); new Audio(URL.createObjectURL(await r.blob())).play();}catch{}});
$('#nextSpeak').addEventListener('click',()=>{if(!speakCorrect.has(speakIndex))return; if(speakIndex===cards.length-1){if(speakCorrect.size===cards.length){completeMode('speak'); showClear('まねっこスピークを 3つ クリアしたよ！','home'); return;} speakIndex=0;} else speakIndex++; renderSpeak();});
let speakRecorder, speakChunks=[];
$('#speakPractice').addEventListener('click',async()=>{const btn=$('#speakPractice'), status=$('#speakResult'); if(speakRecorder?.state==='recording'){speakRecorder.stop();return;} try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}); speakChunks=[]; speakRecorder=new MediaRecorder(stream); speakRecorder.ondataavailable=e=>speakChunks.push(e.data); speakRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop()); btn.textContent='🎙️ いってみる'; status.textContent='はつおんを きいているよ…'; try{const c=cards[speakIndex]; const r=await fetch(`/api/pronounce?expected=${encodeURIComponent(c.en)}`,{method:'POST',headers:{'Content-Type':speakRecorder.mimeType||'audio/webm'},body:new Blob(speakChunks,{type:speakRecorder.mimeType||'audio/webm'})}); const d=await r.json(); status.textContent=d.feedback||'もういちど やってみよう。'; status.className='result '+(d.matched?'ok':'ng'); if(d.matched){speakCorrect.add(speakIndex); $('#nextSpeak').disabled=false;} else {$('#nextSpeak').disabled=true; status.textContent+=' もういちど ためしてみよう。';}}catch{status.textContent='うまく ききとれなかったよ。';}}; speakRecorder.start(); btn.textContent='⏹ おわる'; status.textContent='いってみよう！'; setTimeout(()=>{if(speakRecorder?.state==='recording')speakRecorder.stop()},2500);}catch{status.textContent='マイクが つかえないようです。';}});
function renderPair(){const c=cards[pairIndex]; $('#pairWord').textContent=c.en; $('#pairCount').textContent=`${pairIndex+1} / ${cards.length}`; $('#pairResult').textContent=''; $('#pairResult').className='result'; $('#nextPair').disabled=true; const opts=[c,...cards.filter((_,i)=>i!==pairIndex)].sort(()=>Math.random()-.5); $('#pairChoices').innerHTML=opts.map(x=>`<button class="choice image-choice" data-answer="${x.en}"><img src="${x.img}" alt="${x.jp}"><span>${x.jp}</span></button>`).join(''); document.querySelectorAll('#pairChoices .choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#pairChoices .choice').forEach(x=>x.disabled=true); const ok=b.dataset.answer===c.en; if(ok) pairCorrect.add(pairIndex); b.classList.add(ok?'correct':'wrong'); if(!ok) document.querySelector(`#pairChoices [data-answer="${c.en}"]`).classList.add('correct'); $('#pairResult').textContent=ok?'せいかい！ ぴったりペアだね 🎉':`おしい！ せいかいの 絵は「${c.jp}」だよ。もう一周してみよう。`; $('#pairResult').classList.add(ok?'ok':'ng'); $('#nextPair').disabled=false;}));}
$('#nextPair').addEventListener('click',()=>{if(pairIndex===cards.length-1){if(pairCorrect.size===cards.length){completeMode('pair'); showClear('えとことばペアを 3つ ぜんぶ正解したよ！','home'); return;} pairCorrect.clear(); pairIndex=0; renderPair(); return;} pairIndex++; renderPair();});
let analysisIndex=0, analysisRecorder, analysisChunks=[];
function stopOnSilence(stream, recorder, maxMs){const ctx=new AudioContext(),source=ctx.createMediaStreamSource(stream),analyser=ctx.createAnalyser(),data=new Uint8Array(analyser.fftSize);source.connect(analyser);let started=false,silentSince=0,startedAt=performance.now();const tick=()=>{if(recorder.state!=='recording'){ctx.close();return;}analyser.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n;}const rms=Math.sqrt(sum/data.length);const now=performance.now();if(rms>.025) {started=true;silentSince=0;} else if(started){silentSince ||= now;if(now-silentSince>=1000){recorder.stop();ctx.close();return;}}if(now-startedAt>=maxMs){recorder.stop();ctx.close();return;}requestAnimationFrame(tick);};requestAnimationFrame(tick);}
const analysisWords=[{en:'cat',label:'cat',sounds:'k æ t'},{en:'dog',label:'dog',sounds:'d ɔ g'},{en:'apple',label:'apple',sounds:'æ p əl'},{en:'How are you today?',label:'How are you',sounds:'h aʊ ɑr j u təˈdeɪ'},{en:'I would like a cup of coffee, please.',label:'Coffee please',sounds:'aɪ wʊd laɪk ə kʌp əv ˈkɔːfi pliz'}];
function renderAnalysis(){const w=analysisWords[analysisIndex]; $('#analysisWord').textContent=w.en; $('#expectedSounds').textContent=w.sounds; document.querySelectorAll('.analysis-tabs span').forEach((x,i)=>x.classList.toggle('active',i===analysisIndex));}
document.querySelectorAll('.analysis-tabs span').forEach((b,i)=>b.addEventListener('click',()=>{analysisIndex=i;renderAnalysis();}));
$('#analysisSample').addEventListener('click',async()=>{const w=analysisWords[analysisIndex];try{const r=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:w.en,target:w.en})});await new Audio(URL.createObjectURL(await r.blob())).play();}catch{}});
$('#analysisRecord').addEventListener('click',async()=>{if(analysisRecorder?.state==='recording'){analysisRecorder.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});analysisChunks=[];analysisRecorder=new MediaRecorder(stream);analysisRecorder.ondataavailable=e=>analysisChunks.push(e.data);analysisRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());$('#analysisRecord').textContent='🎙️ 録音して判定';$('#analysisStatus').textContent='分析中…';try{const expected=analysisWords[analysisIndex].en;const r=await fetch(`/api/pronounce?expected=${expected}`,{method:'POST',headers:{'Content-Type':analysisRecorder.mimeType||'audio/webm'},body:new Blob(analysisChunks,{type:analysisRecorder.mimeType||'audio/webm'})});const d=await r.json();$('#analysisScore').textContent=Number.isFinite(Number(d.score))?Math.round(Number(d.score)):'--';$('#analysisSummary').textContent=d.matched?'いい発音です。細かい音も確認できます。':'もう少し練習してみましょう。';$('#heardSounds').textContent=d.transcript||'（聞き取れませんでした）';const errors=d.differences?.errors||[];$('#analysisErrors').textContent=d.analysis==='openpronounce'?(errors.length?errors.slice(0,3).map(e=>`${e.word||expected}: ${e.expected||'--'} → ${e.actual||'（なし）'}`).join(' / '):'音素エラーは見つかりませんでした。'):'音素比較はOpenPronounce接続時に表示します。';$('#analysisStatus').textContent=(d.analysis==='openpronounce'?'OpenPronounce分析：':'簡易分析：')+(d.feedback||'講評を確認してください。');}catch{$('#analysisStatus').textContent='分析できませんでした。もう一度試してください。';}};analysisRecorder.start();$('#analysisRecord').textContent='⏹ 録音をとめる';$('#analysisStatus').textContent='録音中…';stopOnSilence(stream,analysisRecorder,analysisWords[analysisIndex].en.length>10?6000:2500);}catch{$('#analysisStatus').textContent='マイクが使えません。';}});
renderAnalysis();
$('.analysis-tabs').innerHTML=analysisWords.map(w=>`<span>${w.label}</span>`).join(''); document.querySelectorAll('.analysis-tabs span').forEach((b,i)=>b.addEventListener('click',()=>{analysisIndex=i;renderAnalysis();})); renderAnalysis();
const analysisRing=$('.score-ring'); analysisRing.insertAdjacentHTML('afterend',`<div id="analysisScoreCompare" style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0 18px;text-align:center"><div style="background:#f3f7fa;border-radius:12px;padding:10px"><small style="display:block;color:#718797">OpenPronounce</small><strong id="analysisOpenScore" style="font-size:24px">--</strong><span style="font-size:11px;color:#718797"> / 100</span></div><div style="background:#fff1ea;border-radius:12px;padding:10px"><small style="display:block;color:#b15a38">AI（Luna）</small><strong id="analysisLunaScore" style="font-size:24px;color:#df5d2e">--</strong><span style="font-size:11px;color:#b15a38"> / 100</span></div></div><div id="analysisPhoneDetail" style="margin:0 0 14px;padding:12px 14px;background:#f8fbfd;border-radius:12px;font-size:13px;line-height:1.7">音素比較は録音後に表示します。</div>`);
$('#analysis h2').textContent='発音分析';
const originalFetch=window.fetch.bind(window); window.fetch=async(...args)=>{const response=await originalFetch(...args); const url=String(args[0]?.url||args[0]||''); if(url.includes('/api/pronounce')) response.clone().json().then(d=>{if(d.analysis?.startsWith('openpronounce')){$('#analysisOpenScore').textContent=Math.round(Number(d.openpronounceScore??d.score??0));$('#analysisLunaScore').textContent=Math.round(Number(d.score??0));const diff=d.differences||{};const expected=(diff.expected_phones||[]).flat().join(' '),heard=(diff.heard_phones||[]).join(' '),errors=diff.errors||[];$('#analysisPhoneDetail').innerHTML=`<b>音素比較</b><br>お手本：/${expected||'--'}/<br>聞こえた音：/${heard||'--'}/<br><span style="color:${errors.length?'#c95b3f':'#2d8a63'}">${errors.length?`エラー ${errors.length}件：${errors.slice(0,3).map(e=>`${e.word||''} ${e.expected||'--'} → ${e.actual||'（なし）'}`).join(' / ')}`:'音素エラーなし'}</span>`;}}).catch(()=>{}); return response;};
$('#analysisErrors').style.display='none'; $('#analysisSummary').style.display='none'; $('#analysisLunaScore').insertAdjacentHTML('afterend','<div id="analysisLunaFeedback" style="font-size:11px;line-height:1.35;color:#a84e32;margin-top:5px">判定後に講評を表示</div>');
const analysisLabelFetch=window.fetch.bind(window); window.fetch=async(...args)=>{const response=await analysisLabelFetch(...args); const url=String(args[0]?.url||args[0]||''); if(url.includes('/api/pronounce')) response.clone().json().then(d=>{if(d.analysis?.startsWith('openpronounce')){$('#analysisErrors').style.display='none';$('#analysisLunaFeedback').textContent=d.feedback||'講評を確認してください。';$('#analysisStatus').textContent='OpenPronounce＋Luna分析';}}).catch(()=>{}); return response;};
const analysisCard=$('.analysis-card'),analysisTabs=$('.analysis-tabs'),analysisWord=$('.analysis-word'),analysisDetail=$('.analysis-detail'),analysisCompare=$('#analysisScoreCompare'),analysisActions=$('.analysis-actions'),analysisStatus=$('#analysisStatus'); $('#analysisPhoneDetail').style.display='none'; analysisCard.insertBefore(analysisTabs,analysisCard.firstChild); analysisCard.append(analysisWord,analysisDetail,analysisRing,analysisCompare,analysisActions,analysisStatus);
analysisRing.insertAdjacentHTML('beforebegin','<div id="analysisGraphs" style="display:none;margin:14px 0;background:#fbfcfd;border:1px solid #e7eef3;border-radius:14px;padding:12px 14px"><div style="font-weight:800;font-size:13px;margin-bottom:6px">音素トレース（お手本とあなた）</div><svg id="phonemeGraph" viewBox="0 0 520 110" style="width:100%;height:110px;background:#fff;border-radius:8px"></svg><div style="display:flex;gap:14px;font-size:11px;color:#718797;margin:4px 0 14px"><span style="color:#3f82d9">━ お手本</span><span style="color:#f07845">━ あなた</span></div><div style="font-weight:800;font-size:13px;margin-bottom:6px">Pitch（声の高さ）</div><svg id="pitchGraph" viewBox="0 0 520 110" style="width:100%;height:110px;background:#fff;border-radius:8px"></svg><small style="color:#718797">声の高さの変化。英語の抑揚や語尾の上がり下がりを確認できます。</small></div>');
function drawAnalysisGraph(id,series,other=[]){const svg=document.getElementById(id);if(!svg||!series?.length)return;const all=[...series,...other].filter(Number.isFinite),min=Math.min(...all),max=Math.max(...all),range=max-min||1;const path=a=>a.map((v,i)=>`${i?'L':'M'} ${(i/(a.length-1||1)*500+10).toFixed(1)} ${(100-(v-min)/range*82).toFixed(1)}`).join(' ');svg.innerHTML=`<path d="${path(other)}" fill="none" stroke="#3f82d9" stroke-width="3" stroke-linecap="round"/><path d="${path(series)}" fill="none" stroke="#f07845" stroke-width="3" stroke-linecap="round"/>`;}
function resetAnalysisResult(){['analysisScore','analysisOpenScore','analysisLunaScore'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent='--';}); $('#analysisSummary').textContent='声を録音して、発音を分析してみよう。'; $('#heardSounds').textContent='--'; $('#analysisPhoneDetail').textContent='音素比較は録音後に表示します。'; $('#analysisLunaFeedback').textContent='判定後に講評を表示'; $('#analysisStatus').textContent='録音して判定できます。';}
document.querySelectorAll('.analysis-tabs span').forEach(b=>b.addEventListener('click',resetAnalysisResult));
document.querySelectorAll('.analysis-tabs span').forEach(b=>b.addEventListener('click',()=>{const g=$('#analysisGraphs');if(g)g.style.display='none';const p=$('#phonemeGraph'),q=$('#pitchGraph');if(p)p.innerHTML='';if(q)q.innerHTML='';}));
const analysisGraphFetch=window.fetch.bind(window); window.fetch=async(...args)=>{const response=await analysisGraphFetch(...args);const url=String(args[0]?.url||args[0]||'');if(url.includes('/api/pronounce'))response.clone().json().then(d=>{if(d.analysis?.startsWith('openpronounce')){const diff=d.differences||{},prosody=d.prosody||{};$('#analysisGraphs').style.display='block';drawAnalysisGraph('phonemeGraph',diff.transcribed_vector||[],diff.expected_vector||[]);drawAnalysisGraph('pitchGraph',prosody.f0||[],prosody.reference_f0||[]);}}).catch(()=>{});return response;};
const graphBox=$('#analysisGraphs'); graphBox.insertAdjacentHTML('afterbegin','<button id="analysisGraphToggle" style="width:100%;border:0;background:none;color:#3f82d9;text-align:left;font-weight:800;padding:4px 0;cursor:pointer">＋ 詳細グラフを表示</button>'); const graphParts=()=>Array.from(graphBox.children).slice(1); graphParts().forEach(el=>el.style.display='none'); $('#analysisGraphToggle').addEventListener('click',()=>{const open=graphBox.dataset.open==='1';graphBox.dataset.open=open?'0':'1';graphParts().forEach(el=>el.style.display=open?'none':'');$('#analysisGraphToggle').textContent=open?'＋ 詳細グラフを表示':'− 詳細グラフを隠す';});
const scoreCompare=$('#analysisScoreCompare'),openScoreBox=scoreCompare.children[0],lunaCommentBox=scoreCompare.children[1]; openScoreBox.remove(); scoreCompare.style.gridTemplateColumns='150px 1fr'; scoreCompare.style.alignItems='center'; scoreCompare.style.textAlign='left'; scoreCompare.prepend(analysisRing); analysisRing.style.margin='0 auto'; $('#analysisLunaScore').style.display='none'; $('#analysisLunaScore').nextElementSibling.style.display='none'; lunaCommentBox.style.background='#fff1ea'; lunaCommentBox.style.textAlign='left';
lunaCommentBox.innerHTML='<small style="display:block;color:#b15a38">AI（Luna）のコメント</small><div id="analysisLunaFeedback" style="font-size:12px;line-height:1.5;color:#a84e32;margin-top:8px">判定後に講評を表示</div>';
const todayModes=['quiz','pair','speak','cards']; let todayIndex=0;
function renderToday(){todayIndex=Math.floor(Math.random()*todayModes.length); $('#todayCount').textContent='ランダム'; $('#todayMessage').textContent={quiz:'絵を見て、英単語をえらぼう！',pair:'絵と英単語をつなごう！',speak:'英単語をまねして発音しよう！',cards:'カードでことばをおぼえよう！'}[todayModes[todayIndex]];}
$('#todayStart').addEventListener('click',()=>showView(todayModes[todayIndex]));
let audio;
$('.sound').addEventListener('click', async () => {
  const c = cards[cardIndex]; $('#speakStatus').textContent = 'おてほんの おとを じゅんび中…';
  try { const response = await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:c.en})}); if (!response.ok) throw new Error('speech failed'); audio = new Audio(URL.createObjectURL(await response.blob())); await audio.play(); $('#speakStatus').textContent = 'おてほんを きいたよ'; } catch { $('#speakStatus').textContent = 'おとを じゅんびできませんでした（API設定を確認）'; }
});
let recorder, chunks=[];
$('#speakWord').addEventListener('click', async () => {
  const button = $('#speakWord'); const status = $('#speakStatus');
  if (recorder?.state === 'recording') { recorder.stop(); return; }
  try {
    const stream = await navigator.mediaDevices.getUserMedia({audio:true}); recorder = new MediaRecorder(stream); chunks=[]; recorder.ondataavailable=e=>chunks.push(e.data); recorder.onstop=async()=>{ stream.getTracks().forEach(t=>t.stop()); button.classList.remove('recording'); button.querySelector('span').textContent='いってみる'; status.textContent='はつおんを きいているよ…'; try { const result=await fetch(`/api/pronounce?expected=${encodeURIComponent(cards[cardIndex].en)}`,{method:'POST',headers:{'Content-Type':recorder.mimeType||'audio/webm'},body:new Blob(chunks,{type:recorder.mimeType||'audio/webm'})}); const data=await result.json(); status.textContent=data.feedback||'もういちど チャレンジしてみよう。'; status.style.color=data.matched?'#279b78':'#d75d72'; } catch { status.textContent='うまく ききとれなかったよ。もういちど やってみよう。'; } }; recorder.start(); button.classList.add('recording'); button.querySelector('span').textContent='おわる'; status.textContent='いってみよう！'; setTimeout(()=>{if(recorder?.state==='recording') recorder.stop()},2500);
  } catch { status.textContent='マイクが つかえないようです。おてほんを きいてみよう。'; }
});
// Realtime講評が表示されたら、単語を明示して自動読み上げする。
let lastSpokenFeedback = $('#speakResult')?.textContent?.trim() || '';
const speakFeedbackObserver = new MutationObserver(async () => {
  const text = $('#speakResult')?.textContent?.trim() || '';
  if (!text || text === lastSpokenFeedback || text.includes('きいているよ') || text.includes('いってみよう')) return;
  lastSpokenFeedback = text;
  const target = cards[speakIndex]?.en;
  try {
    const response = await fetch('/api/speak', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({text, target})});
    if (response.ok) await new Audio(URL.createObjectURL(await response.blob())).play();
  } catch {}
});
// 判定結果はLunaのテキストのみ表示し、自動読み上げは行わない。
const childSpeakFetch=window.fetch.bind(window); window.fetch=async(input,init)=>{let url=String(input?.url||input||'');if(document.querySelector('#speak.active')&&url.includes('/api/pronounce')&&!url.includes('profile='))url+=(url.includes('?')?'&':'?')+'profile=child';return childSpeakFetch(url,init);};
renderGenres();
renderCard();
